# Generated by Django 2.2.15 on 2020-09-22 15:25

from django.db import migrations, models
import django.db.models.deletion
import geonode.people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0028_auto_20200115_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSO2Profile',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='people.Profile')),
                ('preferred_username', models.CharField(blank=True, help_text='Preferred Username', max_length=4096, null=True, verbose_name='Preferred Username')),
                ('employee_number', models.CharField(blank=True, help_text='Employee Number', max_length=2024, null=True, verbose_name='Employee Number')),
                ('fiscal_code', models.CharField(blank=True, help_text='Fiscal Code', max_length=32, null=True, verbose_name='Fiscal Code')),
                ('department', models.CharField(blank=True, help_text='Department', max_length=4096, null=True, verbose_name='Department')),
                ('authmethod', models.CharField(blank=True, help_text='AUTHMETHOD', max_length=4096, null=True, verbose_name='AUTHMETHOD')),
                ('isdirigente', models.BooleanField(default=False, help_text='ISDIRIGENTE', verbose_name='ISDIRIGENTE')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('people.profile',),
            managers=[
                ('objects', geonode.people.models.ProfileUserManager()),
            ],
        ),
    ]
