# Generated by Django 2.2.15 on 2020-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wso2_openid', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WSO2Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department Name', max_length=4096, verbose_name='Department Name')),
                ('label', models.CharField(blank=True, help_text='Department Label', max_length=4096, null=True, verbose_name='Department Label')),
                ('is_allowed', models.BooleanField(default=True, help_text='Department is Allowed', verbose_name='Department is Allowed')),
            ],
        ),
    ]
